version: '3'
services:
  web:
    build: 
      context : .
      dockerfile : Dockerfile
    ports:
      - "8080:8080"
    links:
      - "bd"
  bd:
    build: 
      context : .
      dockerfile : Dockerfilebd
    ports:
      - "9001:9001"
    #image: "progcomp_bd"